### ISSUE TITLE
image is not displaying on server while working on localhost

### ISSUE THREAD

**Issue by ankitchauhan477** [kevbaldwyn/image#24]
using this package on localhost is going perfectly fine ... No issues are there
But when I switch to server imag is not being displayed over there on browser.

tried alot ... checked almost every possible configuration

**Comment by kevbaldwyn** [comment]
Without more information its hard to help. Does your server have image magic / gd installed? Are you getting any errors? There could be a number of reasons for it not working.

**Comment by ankitchauhan477** [comment]
Gd and image magic are installed on server. I'd checked that with the help of "echo"

**Comment by ankitchauhan477** [comment]
Their might be some other reason. I'm not getting. Do help sir.

**Comment by iveoles** [comment]
Could you give the version of:

GD
Image Magic
Operating System
PHP
Web Server (nginx or Apache)
Framework (Laravel or Fuel)

Could you confirm the files are being uploaded to a folder and are present on the server. 
Could you then confirm they're being created in the app/storage/cache/images folder after being accessed in the browser.

If possible, could you provide a link to an image that is appearing as broken?

Once they've all been ruled out we can investigate further.

**Comment by ankitchauhan477** [comment]
GD -> 2.1.0
Operating System -> Windows 7(64-bit)
PHP -> 5.5.12
Web Server -> Apache 2.4.9
Framework -> Laravel

yes, I do confirm that all files are being uploaded and are present on the server.
on localhost they are being created on app/storage/cache/images folder but on server they are not being created/stored on cache folder.

**Comment by kevbaldwyn** [comment]
Is the cache directory writeable by php? Does the images directory exist? If so is it writeable?

**Comment by ankitchauhan477** [comment]
Images directory do exist but how do i know is it writable or not ?

**Comment by kevbaldwyn** [comment]
if you run ls -l from the parent directory who is the owner and what are the permissions? Ideally you should want the directory writeable by php / the webserver (likely to be www-data) and the permission 0755. You can set them like this (from the cache dir):

  chown www-data:www-data ./images

and 

  chmod 755 ./images

**Comment by ankitchauhan477** [comment]
Its on hostgator.com and its placed in public html directory ... according to amazon instance it is on directory /var/www/html ... and rest other files are at www directory outside html folder.

yes permissions to folder is 777 full writes are provided

anyways now I'd solved that using intervention sir
