### ISSUE TITLE
Laravel 5x compatibility?

### ISSUE THREAD

**Issue by T2theC** [kevbaldwyn/image#28]
Just found this. Looks amazing. Thanks for putting together.

A quickie... It's it L5 compatible?

Thanks. Keep it up!

**Comment by kevbaldwyn** [comment]
Thanks! Not tested it with L5 - not used L5 yet, been working on another large non-laravel project for about 18months so not finding the time at the moment to maintain the Laravel side to this project. Can't see any reason why it wouldn't work assuming there has been no major change to the L5 service providers api.

**Comment by T2theC** [comment]
Sweet. I will have a play and send over a pull request if I get it going. I believe the major changes for packages is the way that config files are stored etc. I'll be looking to implement in a few weeks. I'll keep you posted.

Thanks again.

**Comment by Luppakorva** [comment]
@movostudios 
Wondering did you get it to work with L5? I tried it myself but no luck, if you did would you care to give some pointers how to make it compatible?

**Comment by movostudios** [comment]
Hi @Luppakorva . I didn't to be honest. It most cases though, you need to make changes to the Service Provider. The config files that are published in 4 are in a different location to 5. Quite often that is all you need to do. I don't think this project would be any different.

**Comment by Luppakorva** [comment]
Hello @movostudios and thanks for getting back to me! Being honest I have no idea how to do the changes to the service provider yet but going to look into it :). Quite new to Laravel myself and much of it is still cloudy for a beginner such as myself.  But again thanks for the tips. I'll try to get it working!
